Fix crash in transactions screen
Was getting a crash on transactions screen and it seems
it's from not being able to save `List<Account>` during
`rememberSaveable` process. Need to provide custom
saving mechanism but in the short time I spent trying to do that,
couldn't figure it out so not saving it for now.

Stack trace
```
java.lang.IllegalArgumentException: Parcel: unknown type for value Account(name=All Accounts, fullName=All Accounts, level=0, selected=true)
                                                                                                    	at android.os.Parcel.getValueType(Parcel.java:2455)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2354)
                                                                                                    	at android.os.Parcel.writeList(Parcel.java:1415)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2506)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2362)
                                                                                                    	at androidx.compose.runtime.ParcelableSnapshotMutableState.writeToParcel(ParcelableSnapshotMutableState.kt:30)
```